### ISSUE TITLE
splash screen freeze issue

### ISSUE THREAD

**Issue by bibash28** [TalaoDAO/credible#222]
Splash screen freezes for 5 seconds

**Comment by hawkbee1** [comment]
The issue is here: 

``` dart
    final result = await Future.any([
      DIDKitProvider.instance.verifyCredential(vcStr, optStr),
      Future.delayed(const Duration(seconds: 4))
    ]);

```
verifyCredential is a future but is handled as a synchronous call, thus freezing the application.
Some thread about this kind of issues:
https://github.com/dart-lang/sdk/issues/37022
https://github.com/dart-lang/sdk/issues/48532
https://stackoverflow.com/questions/65865190/flutter-dart-ffi-aplication-freezes-during-processing-external-library-metho
