### ISSUE TITLE
Fix localization and improve code 

### ISSUE THREAD

**Issue by TalebRafiepour** [TalaoDAO/credible#230]

**Comment by bibash28** [comment]
1. cubit/view naming convention and state cubit logic separation
2. packages in alphabetic order
3. handle walletTypes with enum
4. Pass Instances to cubit rather than directly calling from Cubit e.g SecureStorageProvider.instance
5. Constants and SecureStorageKeys are coinciding,, let's combine it
6. Localisation side by side. 
7. User-friendly error text in the snack bar
8. Remove scan/bloc from code... unused code
9. I see that you are adding localization in de, es, fr and it too. You don't have to. You just need to add in en.
10. Why isEnterprise always false when the state is not ProfileStateDefault?
11. I see that you are passing isEnterprise value in screens... I suggest to add isEnterPrise in ProfileModel (Ticket added)
12. Default should be PersonalWallet in ChooseWalletCubit....

**Comment by hawkbee1** [comment]
We don't need a linter, we have @bibash28 :-)

1. cubit/view naming convention and state cubit logic separation **=> YES**
3. packages in alphabetic order **=> YES. I think good venture linter is dealing with this**
4. handle walletTypes with enum **=> Not sure. isEnterpriseWallet is so self-explanatory  (renaming isEnterpriseUser ?) **
5. Pass Instances to cubit rather than directly calling from Cubit e.g SecureStorageProvider.instance **For easier testing**
6. Constants and SecureStorageKeys are coinciding,, let's combine it **=> I wonder. If we delete from Constants what's rightfully belonging to Secure Storage, Secure Storage becomes more autonomous.   **

I will continue later. @TalebRafiepour what do you think ?

**Comment by TalebRafiepour** [comment]
@hawkbee1  @bibash28 
I agree with both of you
Thanks for your good comments

**Comment by bibash28** [comment]
@hawkbee1 
3. We have walletTypes as List [Personal, EnterPrise].. while operating we are using walletType[0] for Personal.. that is too confusing..
Better to use enum WalleType{Personal, EnterPrise}.. So that I can operate using walletType.Personal

**Comment by bibash28** [comment]
13. Looks like DidCubit's purpose is not justified...

DidCubit should be defined from AppWidget and we should set did data for both personal and enterprise from onboarding page using DidCubit...

And we should not allow users to bypass onboarding if we only have a key.. since did is needed.. also after the enterprise option, other things are required to reach the credential page...

**Comment by bibash28** [comment]
14. Enterprise self credential generation issue(Ticket added)
15. I chose the enterprise option with personal data. Later I cannot add company details in drawer(Ticket added)
16. After resetting  wallet navigation to the incorrect page(Ticket added)
